#!/bin/sh
# Copyright (C) 2026 huchd0 <https://github.com/huchd0/luci-app-netwiz>
# Licensed under the GNU General Public License v3.0

[ ! -f /etc/config/netwiz ] && touch /etc/config/netwiz

delete_fw_rule() {
    local target_name="$1"
    local sec_type="${2:-rule}"
    local idx=0
    while uci -q get firewall.@${sec_type}[$idx] >/dev/null; do
        local name=$(uci -q get firewall.@${sec_type}[$idx].name)
        if [ -n "$name" ] && [ "${name#$target_name}" != "$name" ]; then
            uci delete firewall.@${sec_type}[$idx]
            continue
        fi
        idx=$((idx+1))
    done
}

case "$1" in
    list)
        echo '{ "get_list": { "show_conns": "boolean" }, "bind": { "mac": "string", "ip": "string", "name": "string", "dept": "string", "no_reload": "boolean" }, "unbind": { "mac": "string", "no_reload": "boolean" }, "apply_dhcp": {}, "get_depts": {}, "save_depts": { "data": "string" }, "fw_set": { "mac": "string", "ip": "string", "blk_en": "boolean", "iso_en": "boolean", "dmz_en": "boolean" } }'
        exit 0
        ;;
    call)
        case "$2" in
            get_list)
                input=$(cat)
                show_conns=$(echo "$input" | jsonfilter -e '@.show_conns' || echo "false")
                
                conn_str=""
                if [ "$show_conns" = "true" ] || [ "$show_conns" = "1" ]; then
                    if [ -f /proc/net/nf_conntrack ]; then
                        conn_str=$(awk '{for(i=1;i<=NF;i++) if($i~/^src=/) {split($i,a,"="); c[a[2]]++; break}} END{for(i in c) print i"="c[i]}' /proc/net/nf_conntrack 2>/dev/null)
                    elif command -v conntrack >/dev/null 2>&1; then
                        conn_str=$(conntrack -L 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i~/^src=/) {split($i,a,"="); c[a[2]]++; break}} END{for(i in c) print i"="c[i]}')
                    fi
                fi

                fw_str=$(uci show firewall 2>/dev/null || true)
                ipv6_neigh=$(ip -6 neigh show 2>/dev/null || true)
                wifi_macs=$(iwinfo 2>/dev/null | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | tr 'A-Z' 'a-z' || true)
                arp_cache=$(ip -4 neigh show 2>/dev/null || cat /proc/net/arp 2>/dev/null | tail -n +2 || true)
                leases=$(cat /tmp/dhcp.leases /var/dhcp.leases /tmp/run/dnsmasq/dhcp.leases /var/lib/misc/dnsmasq.leases 2>/dev/null || true)
                hosts_str=$(cat /tmp/hosts/* /etc/hosts 2>/dev/null || true)
                uci_hosts=$(uci show dhcp 2>/dev/null | grep "\.@host\[" || true)
                ubus_leases=$(ubus call dhcp ipv4leases 2>/dev/null || ubus call odhcpd ipv4leases 2>/dev/null || true)
                gw_ip=$(ip -4 route show default 2>/dev/null | awk '/default/ {print $3}' | head -n1 | tr -d ' \r\n')
                lan_ip=$(ip addr show br-lan 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1 | head -n1 | tr -d ' \r\n')
                [ -z "$lan_ip" ] && lan_ip=$(uci -q get network.lan.ipaddr | cut -d/ -f1 | tr -d ' \r\n')
                lan_mac=$(ip link show br-lan 2>/dev/null | awk '/link\/ether/ {print $2}' | head -n1 | tr 'A-Z' 'a-z')
                [ -z "$lan_mac" ] && lan_mac=$(ip link | awk '/link\/ether/ {print $2}' | head -n1 | tr 'A-Z' 'a-z')
                local_ips=$(ip -4 addr show 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1 | tr '\n' ' ')
                visitor_ips=$(netstat -nt 2>/dev/null | awk '$4 ~ /:(80|443)$/ && $6 ~ /ESTABLISHED/ {split($5, a, ":"); if(a[1]!="") print a[1]}' | sort -u | tr '\n' ' ')
                curr_time=$(date +%s)

                json_data=$(awk -v current_time="$curr_time" -v wifi_str="$wifi_macs" -v arp_str="$arp_cache" -v lease_str="$leases" -v hosts_str="$hosts_str" -v ubus_str="$ubus_leases" -v uci_str="$uci_hosts" -v gw_ip="$gw_ip" -v lan_ip="$lan_ip" -v lan_mac="$lan_mac" -v local_ips_str="$local_ips" -v visitor_ips_str="$visitor_ips" -v conn_str_input="$conn_str" -v fw_str_input="$fw_str" -v ipv6_str="$ipv6_neigh" '
                BEGIN {
                    gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", gw_ip);
                    gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", lan_ip);
                    gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", lan_mac);
                    
                    split(local_ips_str, lip_arr, " ");
                    for(i in lip_arr) if(lip_arr[i] != "" && lip_arr[i] != "127.0.0.1") router_ips[lip_arr[i]] = 1;

                    split(visitor_ips_str, vip_arr, " ");
                    for(i in vip_arr) if(vip_arr[i] != "" && vip_arr[i] != "127.0.0.1") visitor_ips[vip_arr[i]] = 1;

                    if (lan_mac != "" && lan_ip != "") {
                        all_macs[lan_mac] = 1; arp_ip[lan_mac] = lan_ip; arp_online[lan_mac] = 1; ubus_name[lan_mac] = "OpenWrt (Local)";
                    }

                    split(wifi_str, warr, "\n");
                    for(i in warr) if(warr[i]!="") wifi_online[warr[i]]=1;
                    
                    split(ipv6_str, v6arr, "\n");
                    for(i in v6arr) {
                        n_f = split(v6arr[i], f, " ");
                        if(f[1]!="" && f[1]!~/dev/) {
                            v6_ip = f[1]; mac = ""; state_str = v6arr[i];
                            for(j=1; j<=n_f; j++) {
                                if(f[j]=="lladdr" && n_f>=j+1) mac=tolower(f[j+1]);
                                else if(f[j] ~ /^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$/) mac=tolower(f[j]);
                            }
                            if(mac!="" && mac!="00:00:00:00:00:00" && state_str!~/FAILED/) {
                                if(ipv6_map[mac]=="") ipv6_map[mac] = v6_ip;
                                else if(index(ipv6_map[mac], v6_ip) == 0) ipv6_map[mac] = ipv6_map[mac] " " v6_ip;
                                all_macs[mac]=1;
                                if(state_str ~ /REACHABLE|DELAY|PROBE|STALE|router/) arp_online[mac]=1;
                            }
                        }
                    }

                    split(arp_str, aarr, "\n");
                    for(i in aarr) {
                        n_f = split(aarr[i], f, " ");
                        if(f[1]!="" && f[1]!~/IP/) {
                            mac=""; state_str=aarr[i];
                            for(j=1; j<=n_f; j++) {
                                if(f[j]=="lladdr" && n_f>=j+1) mac=tolower(f[j+1]);
                                else if(f[j] ~ /^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$/) mac=tolower(f[j]);
                            }
                            if(mac!="" && mac!="00:00:00:00:00:00") {
                                if (f[1] ~ /^169\.254\./) {
                                    if (arp_ip[mac] == "") arp_ip[mac] = f[1];
                                } else {
                                    arp_ip[mac] = f[1];
                                }
                                if(state_str ~ /REACHABLE|DELAY|PROBE|STALE|0x2/) arp_online[mac]=1;
                                all_macs[mac]=1;
                            }
                        }
                    }

                    split(ubus_str, ulines, "\n");
                    cur_mac = ""; cur_ip = ""; cur_name = ""; cur_valid = -1;
                    for(i=1; i<=length(ulines); i++) {
                        line = ulines[i];
                        if (line ~ /"mac":/) { split(line, p, "\""); cur_mac = tolower(p[4]); }
                        else if (line ~ /"ip":/) { split(line, p, "\""); cur_ip = p[4]; }
                        else if (line ~ /"hostname":/) { split(line, p, "\""); cur_name = p[4]; }
                        else if (line ~ /"valid":/ || line ~ /"expires":/ || line ~ /"leasetime":/) { 
                            split(line, p, ":"); val=p[2]; gsub(/[^0-9]/, "", val); val = val + 0; 
                            if (val > 1000000000) { cur_valid = (val > current_time) ? val - current_time : 0; }
                            else { cur_valid = val; }
                        }
                        else if (line ~ /}/) {
                            if (cur_mac != "") {
                                if (cur_ip != "") leases_ip[cur_mac] = cur_ip;
                                if (cur_name != "" && cur_name != "*" && cur_name != "?") ubus_name[cur_mac] = cur_name;
                                if (cur_valid > 0) {
                                    h = int(cur_valid / 3600); m = int((cur_valid % 3600) / 60); s = cur_valid % 60;
                                    leases_time[cur_mac] = sprintf("%dh %dm %ds", h, m, s);
                                } else if (cur_valid == 0) { leases_time[cur_mac] = "Expired"; }
                                all_macs[cur_mac] = 1;
                            }
                            cur_mac = ""; cur_ip = ""; cur_name = ""; cur_valid = -1;
                        }
                    }

                    split(lease_str, larr, "\n");
                    for(i in larr) {
                        n_f = split(larr[i], f, " ");
                        if(n_f >= 4 && f[2]!="") { 
                            mac=tolower(f[2]);
                            if(f[3]!="") leases_ip[mac]=f[3]; 
                            name = f[4];
                            for(k=5; k<=n_f-1; k++) { name = name " " f[k]; }
                            if(name!="" && name!="*" && name!="?") leases_name[mac]=name;
                            all_macs[mac]=1; 
                            exp_time = f[1] + 0;
                            if (leases_time[mac] == "") {
                                if (exp_time > 1000000000) {
                                    if (exp_time > current_time) {
                                        left = exp_time - current_time;
                                        h = int(left / 3600); m = int((left % 3600) / 60); s = left % 60;
                                        leases_time[mac] = sprintf("%dh %dm %ds", h, m, s);
                                    } else leases_time[mac] = "Expired";
                                } else if (exp_time > 0 && exp_time <= 1000000000) {
                                    left = exp_time;
                                    h = int(left / 3600); m = int((left % 3600) / 60); s = left % 60;
                                    leases_time[mac] = sprintf("%dh %dm %ds", h, m, s);
                                } else if (exp_time == 0) leases_time[mac] = "Infinite";
                            }
                        }
                    }

                    split(hosts_str, harr, "\n");
                    for(i in harr) {
                        split(harr[i], f, " ");
                        if(f[1]!="" && f[2]!="") {
                            if (f[1] ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/) {
                                name = f[2]; sub(/\.lan$/, "", name);
                                if (name != "localhost" && name != "*" && name != "?") ip_to_name[f[1]] = name;
                            }
                        }
                    }

                    split(uci_str, uarr, "\n");
                    for(i in uarr) {
                        idx=index(uarr[i],"=");
                        if(idx>0) {
                            key=substr(uarr[i],1,idx-1); val=substr(uarr[i],idx+1); gsub(/^\047|\047$/, "", val);
                            split(key, kp, ".");
                            if(kp[1]=="dhcp" && kp[2]!="" && kp[3]!="") {
                                h_idx=kp[2]; prop=kp[3];
                                if(prop=="mac"){
                                    gsub(/["\r\n]/, "", val); split(tolower(val), mparts, " "); 
                                    for(m in mparts) uci_mac_list[h_idx] = (uci_mac_list[h_idx]=="" ? "" : uci_mac_list[h_idx] " ") mparts[m];
                                }
                                else if(prop=="ip") uci_ip_map[h_idx]=val;
                                else if(prop=="name") uci_name_map[h_idx]=val;
                                else if(prop=="netwiz_dept") uci_dept_map[h_idx]=val;
                            }
                        }
                    }

                    for (h_idx in uci_mac_list) {
                        split(uci_mac_list[h_idx], mparts, " ");
                        for (m in mparts) {
                            m_mac = mparts[m]; all_macs[m_mac] = 1; is_static_mac[m_mac] = 1;
                            if (uci_ip_map[h_idx] != "") static_ip[m_mac] = uci_ip_map[h_idx];
                            if (uci_name_map[h_idx] != "") uci_name[m_mac] = uci_name_map[h_idx];
                            if (uci_dept_map[h_idx] != "") static_dept[m_mac] = uci_dept_map[h_idx];
                        }
                    }

                    split(fw_str_input, ffw_arr, "\n");
                    for(i in ffw_arr) {
                        line = ffw_arr[i];
                        if (index(line, "firewall.@rule[") == 1) {
                            eq_idx = index(line, "=");
                            if (eq_idx > 0) {
                                prop_full = substr(line, 1, eq_idx - 1); val = substr(line, eq_idx + 1); gsub(/[\047"\r\n]/, "", val);
                                split(prop_full, kp, ".");
                                if (kp[1] == "firewall" && kp[2] != "" && kp[3] != "") {
                                    obj = kp[2]; prop = kp[3];
                                    if (prop == "name" && val ~ /^nw_/) fw_name[obj] = val;
                                }
                            }
                        }
                        if (index(line, "firewall.@redirect[") == 1) {
                            eq_idx = index(line, "=");
                            if (eq_idx > 0) {
                                prop_full = substr(line, 1, eq_idx - 1); val = substr(line, eq_idx + 1); gsub(/[\047"\r\n]/, "", val);
                                split(prop_full, kp, ".");
                                if (kp[1] == "firewall" && kp[2] != "" && kp[3] == "name" && val ~ /^nw_dmz_/) fw_name_dmz[kp[2]] = val;
                            }
                        }
                    }

                    for (obj in fw_name_dmz) {
                        name = fw_name_dmz[obj]; split(name, parts, "_"); mac_clean = tolower(parts[3]);
                        if (length(mac_clean) == 12) { mac = substr(mac_clean,1,2) ":" substr(mac_clean,3,2) ":" substr(mac_clean,5,2) ":" substr(mac_clean,7,2) ":" substr(mac_clean,9,2) ":" substr(mac_clean,11,2); fw_dmz[mac] = 1; }
                    }

                    for (obj in fw_name) {
                        name = fw_name[obj]; split(name, parts, "_"); type = parts[2]; mac_clean = tolower(parts[3]);
                        if (length(mac_clean) == 12) {
                            mac = substr(mac_clean,1,2) ":" substr(mac_clean,3,2) ":" substr(mac_clean,5,2) ":" substr(mac_clean,7,2) ":" substr(mac_clean,9,2) ":" substr(mac_clean,11,2);
                            if (type == "blk") fw_blk[mac] = 1; else if (type == "iso") fw_iso[mac] = 1;
                        }
                    }

                    split(conn_str_input, carr, "\n");
                    for(i in carr) {
                        split(carr[i], p, "=");
                        if(p[1]!="") conn_count[p[1]] = p[2] + 0;
                    }

                    printf "{\"devices\": [";
                    first=1;
                    for(mac in all_macs) {
                        is_online = (arp_online[mac]==1 || wifi_online[mac]==1) ? 1 : 0;
                        ip = arp_ip[mac]; 
                        
                        if(ip == "" || ip ~ /^169\.254\./) {
                            if(leases_ip[mac] != "") ip = leases_ip[mac];
                            else if(static_ip[mac] != "") ip = static_ip[mac];
                        }
                        
                        gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", ip);
                        if(ip=="" && is_online==0) continue;
                        if(ip=="") ip = "Unknown IP";
                        
                        name = uci_name[mac];
                        if(name=="") name = ip_to_name[ip];
                        if(name=="") name = ubus_name[mac];
                        if(name=="") name = leases_name[mac]; 
                        if(name=="") name = "Unknown";
                        
                        l_time = leases_time[mac];
                        if(l_time=="") {
                            if (is_static_mac[mac]==1) l_time = "Static";
                            else if (arp_online[mac]==1) l_time = "Device Addressed IP";
                            else l_time = "-";
                        }

                        v6_val = ipv6_map[mac];
                        gsub(/["\\]/, "", mac); gsub(/\047/, "", mac); gsub(/[\r\n\t]/, "", mac);
                        gsub(/["\\]/, "", ip); gsub(/\047/, "", ip); gsub(/[\r\n\t]/, "", ip);
                        gsub(/["\\]/, "", name); gsub(/\047/, "", name); gsub(/[\r\n\t]/, "", name);
                        gsub(/["\\]/, "", l_time); gsub(/\047/, "", l_time); gsub(/[\r\n\t]/, "", l_time);
                        gsub(/["\\]/, "", v6_val); gsub(/\047/, "", v6_val); gsub(/[\r\n\t]/, "", v6_val);
                        
                        is_static = (is_static_mac[mac]==1) ? "true" : "false";
                        is_gw = (ip != "" && ip == gw_ip) ? "true" : "false";
                        is_local = (ip != "" && router_ips[ip] == 1) ? "true" : "false";
                        is_visitor = (ip != "" && visitor_ips[ip] == 1) ? "true" : "false";
                        b_ip = static_ip[mac]; b_dept = static_dept[mac];
                        
                        gsub(/["\\]/, "", b_ip); gsub(/\047/, "", b_ip); gsub(/[\r\n\t]/, "", b_ip);
                        gsub(/["\\]/, "", b_dept); gsub(/\047/, "", b_dept); gsub(/[\r\n\t]/, "", b_dept);
                        
                        c_count = (conn_count[ip] != "") ? conn_count[ip] : 0;
                        f_blk = (fw_blk[mac]==1) ? "true" : "false";
                        f_iso = (fw_iso[mac]==1) ? "true" : "false";
                        f_dmz = (fw_dmz[mac]==1) ? "true" : "false";

                        if(!first) printf ", ";
                        printf "{\"mac\": \"%s\", \"ip\": \"%s\", \"bound_ip\": \"%s\", \"dept\": \"%s\", \"name\": \"%s\", \"online\": %s, \"is_static\": %s, \"is_gw\": %s, \"is_local\": %s, \"is_visitor\": %s, \"lease\": \"%s\", \"conn_count\": %d, \"fw_block\": %s, \"fw_isolate\": %s, \"fw_dmz\": %s, \"ipv6\": \"%s\"}", mac, ip, b_ip, b_dept, name, (is_online?"true":"false"), is_static, is_gw, is_local, is_visitor, l_time, c_count, f_blk, f_iso, f_dmz, v6_val;
                        first=0;
                    }
                    printf "]}";
                }')
                echo "$json_data"
                exit 0
                ;;
            fw_set)
                input=$(cat)
                mac=$(echo "$input" | jsonfilter -e '@.mac' | tr 'A-Z' 'a-z')
                mac_clean=$(echo "$mac" | tr -d ':')
                ip=$(echo "$input" | jsonfilter -e '@.ip')
                blk_en=$(echo "$input" | jsonfilter -e '@.blk_en')
                iso_en=$(echo "$input" | jsonfilter -e '@.iso_en')
                dmz_en=$(echo "$input" | jsonfilter -e '@.dmz_en')

                [ -z "$mac" ] && exit 0

                delete_fw_rule "nw_blk_${mac_clean}" "rule"
                if [ "$blk_en" = "true" ] || [ "$blk_en" = "1" ]; then
                    uci add firewall rule >/dev/null
                    uci set firewall.@rule[-1].name="nw_blk_${mac_clean}"
                    uci set firewall.@rule[-1].src="lan"
                    uci set firewall.@rule[-1].dest="wan"
                    uci set firewall.@rule[-1].src_mac="$mac"
                    uci set firewall.@rule[-1].family="any"
                    uci set firewall.@rule[-1].target="DROP"
                    uci set firewall.@rule[-1].enabled="1"
                fi

                delete_fw_rule "nw_iso_${mac_clean}" "rule"
                if [ "$iso_en" = "true" ] || [ "$iso_en" = "1" ]; then
                    uci add firewall rule >/dev/null
                    uci set firewall.@rule[-1].name="nw_iso_${mac_clean}"
                    uci set firewall.@rule[-1].src="lan"
                    uci set firewall.@rule[-1].dest="lan"
                    uci set firewall.@rule[-1].src_mac="$mac"
                    uci set firewall.@rule[-1].family="any"
                    uci set firewall.@rule[-1].target="DROP"
                    uci set firewall.@rule[-1].enabled="1"
                fi

                if [ "$dmz_en" = "true" ] || [ "$dmz_en" = "1" ]; then
                    existing_dmz=$(uci -q show firewall | grep -E "\.name='nw_dmz_" | grep -v "nw_dmz_${mac_clean}'" | head -n 1)
                    if [ -n "$existing_dmz" ]; then echo '{"error":"DMZ_OCCUPIED_BY_ANOTHER_DEVICE"}'; exit 1; fi
                    delete_fw_rule "nw_dmz" "redirect"
                    [ -n "$ip" ] && [ "$ip" != "Unknown IP" ] && {
                        uci add firewall redirect >/dev/null
                        uci set firewall.@redirect[-1].name="nw_dmz_${mac_clean}"
                        uci set firewall.@redirect[-1].src="wan"
                        uci set firewall.@redirect[-1].dest="lan"
                        uci set firewall.@redirect[-1].dest_ip="$ip"
                        uci set firewall.@redirect[-1].proto="all"
                        uci set firewall.@redirect[-1].target="DNAT"
                        uci set firewall.@redirect[-1].enabled="1"
                    }
                else
                    delete_fw_rule "nw_dmz_${mac_clean}" "redirect"
                fi

                uci commit firewall
                /etc/init.d/firewall reload </dev/null >/dev/null 2>&1 &
                
                if [ "$blk_en" = "true" ] || [ "$blk_en" = "1" ]; then
                    if command -v iptables >/dev/null 2>&1; then iptables -I FORWARD 1 -m mac --mac-source $mac -j DROP >/dev/null 2>&1; fi
                    if command -v ip6tables >/dev/null 2>&1; then ip6tables -I FORWARD 1 -m mac --mac-source $mac -j DROP >/dev/null 2>&1; fi
                    if command -v nft >/dev/null 2>&1; then nft insert rule inet fw4 forward ether saddr $mac drop >/dev/null 2>&1; fi
                fi
                if [ "$iso_en" = "true" ] || [ "$iso_en" = "1" ]; then
                    if command -v iptables >/dev/null 2>&1; then iptables -I FORWARD 1 -m mac --mac-source $mac -d 192.168.0.0/16 -j DROP >/dev/null 2>&1; fi
                    if command -v nft >/dev/null 2>&1; then nft insert rule inet fw4 forward ether saddr $mac ip daddr 192.168.0.0/16 drop >/dev/null 2>&1; fi
                fi
                
                if command -v conntrack >/dev/null 2>&1; then
                    [ -n "$ip" ] && [ "$ip" != "Unknown IP" ] && conntrack -D -s "$ip" >/dev/null 2>&1
                fi
                for vap in $(ubus list | grep hostapd); do ubus call "$vap" del_client '{"addr":"'"$mac"'", "reason":5, "deauth":true, "ban_time":0}' >/dev/null 2>&1; done

                echo '{"result":0}'
                exit 0
                ;;
            bind)
                input=$(cat)
                mac=$(echo "$input" | jsonfilter -e '@.mac' | tr 'A-Z' 'a-z')
                ip=$(echo "$input" | jsonfilter -e '@.ip')
                name=$(echo "$input" | jsonfilter -e '@.name')
                dept=$(echo "$input" | jsonfilter -e '@.dept')
                no_reload=$(echo "$input" | jsonfilter -e '@.no_reload')

                [ -z "$mac" ] || [ -z "$ip" ] && exit 0
                
                if ! echo "$ip" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
                    echo '{"error":"INVALID_IP_FORMAT"}'
                    exit 1
                fi

                safe_name=$(echo "$name" | sed 's/[^a-zA-Z0-9-]/-/g' | sed 's/-\{2,\}/-/g' | sed 's/^-//; s/-$//')
                if [ -z "$safe_name" ] || [ "$safe_name" = "Unknown" ]; then 
                    safe_name="Dev-$(echo "$mac" | tr -d ':' | cut -c 9-12)"
                fi
                name="$safe_name"

                uci show dhcp | grep -i "\.mac=.*$mac" | cut -d'.' -f2 | while read -r h_idx; do uci delete dhcp.$h_idx 2>/dev/null; done
                uci show dhcp | grep "\.ip='$ip'" | cut -d'.' -f2 | while read -r h_idx; do uci delete dhcp.$h_idx 2>/dev/null; done
                
                new_sect=$(uci add dhcp host)
                uci set dhcp.$new_sect.name="$name"
                uci set dhcp.$new_sect.mac="$mac"
                uci set dhcp.$new_sect.ip="$ip"
                
                ip_suffix=${ip##*.}
                if [ -n "$ip_suffix" ] && [ "$ip_suffix" -eq "$ip_suffix" ] 2>/dev/null; then
                    hostid_val=$(printf "::%04d" "$ip_suffix")
                    uci set dhcp.$new_sect.hostid="$hostid_val"
                fi
                
                if [ -n "$dept" ] && [ "$dept" != "none" ]; then uci set dhcp.$new_sect.netwiz_dept="$dept"; fi
                
                uci commit dhcp
                if [ "$no_reload" != "true" ] && [ "$no_reload" != "1" ]; then /etc/init.d/dnsmasq reload >/dev/null 2>&1; fi
                echo '{"result":0}'
                exit 0
                ;;
            unbind)
                input=$(cat)
                mac=$(echo "$input" | jsonfilter -e '@.mac' | tr 'A-Z' 'a-z')
                no_reload=$(echo "$input" | jsonfilter -e '@.no_reload')
                [ -z "$mac" ] && exit 0
                
                uci show dhcp | grep -i "\.mac=.*$mac" | cut -d'.' -f2 | while read -r h_idx; do uci delete dhcp.$h_idx 2>/dev/null; done
                
                mac_clean=$(echo "$mac" | tr -d ':' | tr 'a-z' 'A-Z')
                delete_fw_rule "nw_blk_${mac_clean}" "rule"
                delete_fw_rule "nw_iso_${mac_clean}" "rule"
                delete_fw_rule "nw_dmz_${mac_clean}" "redirect"
                uci commit firewall
                /etc/init.d/firewall reload >/dev/null 2>&1

                uci commit dhcp
                if [ "$no_reload" != "true" ] && [ "$no_reload" != "1" ]; then /etc/init.d/dnsmasq reload >/dev/null 2>&1; fi
                echo '{"result":0}'
                exit 0
                ;;
            apply_dhcp)
                /etc/init.d/dnsmasq reload >/dev/null 2>&1
                echo '{"result":0}'
                exit 0
                ;;
            get_depts)
                val=$(uci -q get netwiz.global.depts_json)
                [ -z "$val" ] && val="[]"
                echo "{\"depts\": $val}"
                exit 0
                ;;
            save_depts)
                input=$(cat)
                json_str=$(echo "$input" | jsonfilter -e '@.data')
                uci -q delete netwiz.global
                uci set netwiz.global=netwiz
                uci set netwiz.global.depts_json="$json_str"
                uci commit netwiz
                echo '{"result":0}'
                exit 0
                ;;
        esac
        ;;
esac
exit 1
