include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Network Setup Wizard
LUCI_DEPENDS:=+luci-base +iwinfo +rpcd +rpcd-mod-iwinfo +luci-compat +ppp-mod-pppoe
PKG_VERSION:=1.5
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
