#!/bin/sh /etc/rc.common
# Copyright (C) 2026 huchd0 <https://github.com/huchd0/luci-app-netwiz>
# Licensed under the GNU General Public License v3.0
# Execution priority must be strictly earlier than 'network' (which is usually 20)
START=15

boot() {
    BAK_FILE="/etc/config/network.netwiz_bak"
    
    if [ -f "$BAK_FILE" ]; then
        logger -t Netwiz "Detect interrupted by power loss. Recovering original WAN protocol..."
        cp "$BAK_FILE" /etc/config/network
        rm -f "$BAK_FILE"
    fi
}
