#!/bin/sh
# Copyright (C) 2026 huchd0 <https://github.com/huchd0/luci-app-netwiz>
# Licensed under the GNU General Public License v3.0

#!/bin/sh
[ "$ACTION" = "change" ] || [ "$ACTION" = "add" ] || exit 0

if [ "$(cat /sys/class/net/$INTERFACE/carrier 2>/dev/null)" = "1" ]; then

    /usr/libexec/netwiz-autodetect.sh >/dev/null 2>&1 </dev/null &
fi
