name: luci-app-netwiz Build IPK & APK

on:
  workflow_dispatch:
    inputs:
      highlights:
        description: '✨ OpenWrt/ImmortalWrt一键安装版更新说明'
        required: false
        default: '常规维护与稳定性更新。'

jobs:
  # 多架构并行编译
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk_version: [ "x86_64-23.05.5", "x86_64-snapshot" ]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build LuCI package
        uses: sbwml/openwrt-gh-action-sdk@main   
        env:
          ARCH: ${{ matrix.sdk_version }}
          PACKAGES: luci-app-netwiz
          NO_REFRESH_CHECK: true

      - name: Prepare Fixed-Name Packages
        run: |
          mkdir -p release_pkgs
          # 化繁为简：找到生成的包并统一命名，找不到也不会报错
          find bin/ -name "luci-app-netwiz*.ipk" -exec cp {} release_pkgs/luci-app-netwiz.ipk \;
          find bin/ -name "luci-app-netwiz*.apk" -exec cp {} release_pkgs/luci-app-netwiz.apk \;

      - name: Upload Artifacts to Cloud
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.sdk_version }}
          path: release_pkgs/*
          compression-level: 0 

  # 二：统一收集并发布
  release:
    needs: build  # 💡 核心指令：必须等上面的 build 彻底完成才执行
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: final_release
          merge-multiple: true # 把多台机器的 ipk 和 apk 合并到这一个文件夹里！

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: NetWiz 最新极速安装版
          body: |
            ### ✨ 最新版发布
            ${{ github.event.inputs.highlights || '持续优化与稳定性更新。' }}
            
            ---
            
            ### 🚀 全平台一键极速安装
            无论你的路由器是 OpenWrt/ImmortalWrt/iStoreOS 23.05 (老版) 还是 25.x (新版)，请使用 SSH 登录路由器终端，**直接复制并运行下方这一行代码**。
            它会自动识别您的系统版本，并自动下载对应格式的安装包完成部署：
            
            ```bash
            wget -qO- [https://raw.githubusercontent.com/$](https://raw.githubusercontent.com/$){{ github.repository }}/master/install.sh | sh
            ```
          # 💡 直接上传文件夹里所有的包
          files: final_release/*
          generate_release_notes: false
